%%% This file was automatically generated by snmpc_mib_to_hrl version 5.6.1
%%% Date: 12-Dec-2020::15:59:29
-ifndef('OTP-TC').
-define('OTP-TC', true).

%% Oids

-define(otpTcModule, [1,3,6,1,4,1,193,19,1,1,2]).


%% Range values


%% Default values

-endif.
